### PR TITLE
Remove redundant images

### PR DESCRIPTION
**Pull request by programming-wolf**
- Remove redundant logo
- Remove text that is not executed anymore

### CODE REVIEW

**Comment by aheusingfeld** [comment]
@programming-wolf did you see my comments in https://github.com/isaqb-org/advanced-template/issues/120?

**Comment by programming-wolf** [comment]
Yes, and I replied to them.

**Review by aheusingfeld — APPROVED** [review]
Looks like a good idea as an intermediate step before moving the JPG to the html-theme

**Comment by programming-wolf** [comment]
Thing is, the "theme" is only css, the image would have to be placed by the original ADOC file, not the theme.

**Pull request merged**
